# Get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

# Create a new book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "Agile Principles"
}

###

# Update a book by id
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Clean Code"
}

###

# Delete a book by id
DELETE http://localhost:3001/books/1 HTTP/1.1